name: Check Python syntax is correct or not using python linter

on:
  push:
    paths: "*.py"

jobs:
  Linter-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout/Clone the code
        run: actions/checkout@v4
          
      - name: Check Python Linter
        run: pip install ruff
        
      - name: Linter Check
        run: ruff check --fix
