name: MyHello
on:
    workflow_dispatch:

jobs:
    Say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Priya Hello
              run: echo "Hello From Priya"

            - name: Avani Hello
              run: echo "Hello from Avani"
